### ISSUE TITLE
Annotation removed by the operator

### ISSUE THREAD

**Issue by trotro** [openshift/loki#303]
**Describe the bug**
After deploying a lokistack I patch the logging-loki route to add an annotation. After some time, the annotation is removed by the operator.

**To Reproduce**
1. Deploy a lokistack
2. Patch the logging-loki route with the annotation `haproxy.router.openshift.io/ip_whitelist: <some ip>`
3. Wait and check the route later, the annotation has been removed

**Expected behavior**
The annotation stays on the route

**Environment:**
 - Openshift 4.14.20
 - Loki Operator 5.9.0 provided by Red Hat

**Comment by xperimental** [comment]
@trotro Just came across this issue. Looking at date and content it looks to me as if this was a template for [this issue](https://issues.redhat.com/browse/LOG-5566) in our JIRA. Is it okay if I close this one in favor of the JIRA issue?

**Comment by trotro** [comment]
Hi @xperimental, the issue you mentionned is related and was created after I talked to Joseph.
Since you resolved it and it should come with v6.0.0 of the operator, you can close (which is already done 😉) this one.
Thanks for your work

**Comment by periklis** [comment]
@trotro This one was backported on the Red Hat builds back to 5.9 and 5.8 or even 5.6 IIRC.
